# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Paul Combal <abonnementspaul@gmail.com>, 2017
# Abdellah B <bahassinea@gmail.com>, 2017
# Aestan <anthony.margerand@protonmail.com>, 2018
# Aurnytoraink <adressetempo@aurny2mail.ddns.net>, 2018
# a270031086f2a0d3514bc0cb507b48f6, 2019
# Seboss666 <sebastien_verdet@seboss666.info>, 2019
# Florian B <florianb3522@gmail.com>, 2019
# Arnaud Ferraris <arnaud.ferraris@gmail.com>, 2019
# roxfr <roxfr@outlook.fr>, 2022
# David D, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: David D, 2023\n"
"Language-Team: French (https://app.transifex.com/calamares/teams/20061/fr/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fr\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Installation du bootloader."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Échec de l'installation de grub, aucune partition définie dans le stockage "
"global"

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Erreur d'installation du chargeur de démarrage"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Le chargeur de démarrage n'a pas pu être installé. La commande "
"d'installation <pre>{!s}</pre> a renvoyé le code d'erreur {!s}."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "Impossible d'écrire le fichier de configuration LXDM"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "Le fichier de configuration LXDM n'existe pas"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "Impossible d'écrire le fichier de configuration LightDM"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "Le fichier de configuration LightDM {!S} n'existe pas"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "Impossible de configurer LightDM"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "Aucun hôte LightDM est installé"

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "Impossible d'écrire le fichier de configuration SLIM"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "Le fichier de configuration SLIM {!S} n'existe pas"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr ""
"Aucun gestionnaire d'affichage n'a été sélectionné pour le module de "
"gestionnaire d'affichage"

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"La liste des gestionnaires d'affichage est vide ou indéfinie à la fois dans "
"globalstorage et displaymanager.conf."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr "La configuration du gestionnaire d'affichage était incomplète"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Configuration du initramfs avec dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Échec de l'exécution de dracut"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Dract a échoué à l'exécution sur la cible et a retourné le code:  "
"{return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Tâche factice de python"

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "Étape factice de python {}"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "Écriture du fstab."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Erreur de configuration"

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr ""
"Aucune partition n'est définie pour être utilisée par <pre>{!s}</pre>."

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr ""
"Aucun point de montage racine n'a été donné pour être utilisé par "
"<pre>{!s}</pre>."

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Aucune configuration <pre>{!s}</pre>n'est donnée pour <pre>{!s}</pre> à "
"utiliser."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "Configuration du GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Configuration de l'horloge matériel."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Configuration de mkinitcpio."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr ""
"Aucune partition n'est définie pour être utilisée pour "
"<pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "Aucun point de montage racine pour <pre>initcpiocfg</pre>."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Configuration du initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Configuration des locales."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Création d'initramfs avec mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Échec de l'exécution de mkinitfs sur la cible"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Le code de sortie était {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Montage des partitions."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr "Erreur interne lors du montage des jeux de données zfs"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "Échec de l'importation de zpool"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "Impossible de déverrouiller zpool"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "Impossible de définir le point de montage zfs"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "erreur de montage zfs"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Sauvegarde de la configuration du réseau en cours."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Configuration du service OpenRC dmcrypt."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Installer les paquets."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Traitement des paquets (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Installation d'un paquet."
msgstr[1] "Installation de %(num)d paquets."
msgstr[2] "Installation de %(num)d paquets."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Suppression d'un paquet."
msgstr[1] "Suppression de %(num)d paquets."
msgstr[2] "Suppression de %(num)d paquets."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Erreur du gestionnaire de paquets"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Le gestionnaire de paquets n'a pas pu préparer les mises à jour. La commande"
" <pre>{!s}</pre> a renvoyé le code d'erreur {!s}."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Le gestionnaire de paquets n'a pas pu mettre à jour le système. La commande "
"<pre>{!s}</pre> a renvoyé le code d'erreur {!s}."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Le gestionnaire de paquets n'a pas pu apporter de modifications au système "
"installé. La commande <pre>{!s}</pre> a renvoyé le code d'erreur {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Configurer le thème Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Installation de données."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Configurer les services OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Impossible d'ajouter le service {name!s} au run-level {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Impossible de retirer le service {name!s} du run-level {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Service-action <code>{arg!s}</code> inconnue pour le service {name!s} dans "
"le run-level {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Impossible de modifier le service"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"L'appel <code> rc-update {arg!s}</code> dans chroot a renvoyé le code "
"d'erreur {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Le runlevel cible n'existe pas"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Le chemin pour le runlevel {level!s} est <code>{path!s}</code>, qui n'existe"
" pas."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Le service cible n'existe pas"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Le chemin pour le service {name!s} est <code>{path!s}</code>, qui n'existe "
"pas."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Configurer les units de systemd"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Impossible de modifier l'unit"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"L'appel <code>systemctl {_action!s}</code> en chroot a renvoyé le code "
"d'erreur {_exit_code!s}"

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "Ne peut pas {_action!s} l'unit systemd <code>{_name!s}</code>."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Remplir les systèmes de fichiers."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "rsync a échoué avec le code d'erreur {}."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Décompression de l'image {}/{}, fichier {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "Commencer à décompresser {}"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "Impossible de décompresser l'image \"{}\""

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "Pas de point de montage pour la partition racine"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage ne contient pas de clé \"rootMountPoint\"."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "Mauvais point de montage pour la partition racine"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "Le point de montage racine est \"{}\", qui n'existe pas."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "Mauvaise configuration unpackfs"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Il n'y a pas d'informations de configuration."

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr ""
"Le système de fichiers pour \"{}\" ({}) n'est pas pris en charge par votre "
"noyau actuel"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "Le système de fichiers source \"{}\" n'existe pas"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Impossible de trouver unsquashfs, assurez-vous que le package squashfs-tools"
" est installé."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "La destination \"{}\" dans le système cible n'est pas un répertoire"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Copie en cours du hostid généré par zfs. "
