# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# strel, 2017
# Guido Grasso <cuquiman97@gmail.com>, 2018
# Adolfo Jayme-Barrientos, 2019
# Miguel Mayol <mitcoes@gmail.com>, 2020
# Pier Jose Gotta Perez <piegope@protonmail.com>, 2020
# Casper, 2023
# Swyter <Swyterzone@gmail.com>, 2024
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Swyter <Swyterzone@gmail.com>, 2024\n"
"Language-Team: Spanish (https://app.transifex.com/calamares/teams/20061/es/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es\n"
"Plural-Forms: nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Instalando el gestor de arranque."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Hubo un error al instalar «grub»; no hay particiones definidas en el "
"almacenamiento global"

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Hubo un error al instalar el gestor de arranque"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"No se pudo instalar el gestor de arranque; la orden de instalación "
"<pre>{!s}</pre> devolvió el código de error {!s}."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "No se puede escribir el archivo de configuración LXDM"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "El archivo de configuracion {!s} de LXDM no existe"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "No se puede escribir el archivo de configuración de LightDM"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "El archivo de configuración {!s} de LightDM no existe"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "No se puede configurar LightDM"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "No hay ningún menú de bienvenida («greeter») de LightDM instalado."

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "No se puede escribir el archivo de configuración de SLIM"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "El archivo de configuración {!s} de SLIM no existe"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr ""
"No se ha elegido ningún gestor de pantalla para el módulo «displaymanager»."

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"La lista de gestores de pantalla está vacía o sin definir tanto en "
"«globalstorage» como en «displaymanager.conf»."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr ""
"La configuración del gestor de pantalla («display manager») estaba "
"incompleta"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Creando el «initramfs» (archivos de arranque) con «dracut»."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "No se pudo ejecutar dracut"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Dracut no pudo ejecutarse en el objetivo con el código de retorno: "
"{return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Tarea de python ficticia."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "Paso ficticio de python {}"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "Escribiendo el «fstab»."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Error de configuración"

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "No hay ninguna partición en <pre>{!s}</pre> que se pueda usar."

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "No hay ningún punto de montaje en <pre>{!s}</pre> que se pueda usar."

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"No se proporciona ninguna configuración de <pre>{!s}</pre> que "
"<pre>{!s}</pre> pueda usar."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "Configurar GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Ajustando el reloj interno del equipo."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Configurando «mkinitcpio»."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "No se definen particiones para <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "No hay un punto de montaje raíz («root») para <pre>initcpiocfg</pre>."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Configurando «initramfs» (archivos de arranque)."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Aplicando la configuración regional."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Creando el «initramfs» con «mkinitfs»."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Hubo un error al ejecutar «mkinitfs» en el destino"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "El código de salida fue {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Montando las particiones."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr ""
"No se pudieron montar los conjuntos de datos («datasets») de zfs por un "
"error interno"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "No se pudo importar el «zpool»"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "No se pudo desbloquear el «zpool»"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "No se pudo establecer el punto de montaje zfs"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "hubo un error con el montaje zfs"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Guardando configuración de red."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Configurando el servicio de arranque cifrado «dmcrypt» para OpenRC "

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Instalar paquetes."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Procesando paquetes (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Instalando un paquete."
msgstr[1] "Instalando %(num)d paquetes."
msgstr[2] "Instalando %(num)d paquetes."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Eliminando un paquete."
msgstr[1] "Eliminando %(num)d paquetes."
msgstr[2] "Eliminando %(num)d paquetes."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Hubo un error del gestor de paquetes"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"El gestor de paquetes no pudo preparar las actualizaciones; la orden "
"<pre>{!s}</pre> devolvió el código de error {!s}."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"El gestor de paquetes no pudo actualizar el sistema; la orden "
"<pre>{!s}</pre> devolvió el código de error {!s}."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"El gestor de paquetes no pudo realizar cambios en el sistema a instalar; la "
"orden <pre>{!s}</pre> devolvió el código de error {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Configurar tema de Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Instalando los datos."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Configurar servicios de OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr ""
"No se puede añadir el servicio {name!s} al nivel de ejecución («run-level») "
"{level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr ""
"No se puede borrar el servicio {name!s} del nivel de ejecución («run-level»)"
" {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Acción del servicio («service-action») desconocida <code>{arg!s}</code> para"
" el servicio {name!s} en el nivel de ejecución («run-level») {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "No se puede modificar el servicio"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> en la raíz cambiada «chroot» ha devuelto el "
"código de error {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "El nivel de ejecución («runlevel») elegido no existe"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"La ruta del nivel de ejecución («runlevel») {level!s} es "
"<code>{path!s}</code>, que no existe."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Parece que el servicio a cambiar no existe"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"La ruta para el servicio {name!s} es <code>{path!s}</code>, que no existe."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Configurar unidades systemd"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "No se puede modificar la unidad"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"<code>systemctl {_action!s}</code> la llamada en chroot devolvió el código "
"de error {_exit_code!s}."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "No se puede {_action!s} unidad systemd<code> {_name!s}</code>."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Rellenando los sistemas de archivos."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "Falló la sincronización mediante «rsync» con el código de error {}."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Desempaquetando la imagen {}/{}, archivo {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "Desempaquetando {}"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "No se pudo desempaquetar la imagen «{}»"

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "Parece que la partición raíz («root») no tiene un punto de montaje"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "El «globalstorage» no contiene una clave «rootMountPoint»."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "El punto de montaje de la partición raíz («root») no es correcto"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "«rootMountPoint» es «{}», que no existe."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "La configuración de «unpackfs» no es correcta"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Parece que no hay información de configuración."

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr ""
"El sistema de archivos de «{}» ({}) no es compatible con el kernel actual"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "El sistema de archivos fuente «{}» no existe"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Parece que «unsquashfs» no está disponible; asegúrate de tener instalado "
"«squashfs-tools»."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "El destino «{}» en el sistema escogido no es una carpeta"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Copiando hostid generado por zfs."
